config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  delete '/ban' => 'reports#approve'
  
  resources :posts, only: [:edit, :create, :update, :destroy]
  resources :forums, only: [:index, :show] do
    get 'page/:page', action: :show, on: :collection
  end
  resources :characters, only: [:show, :index]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy]
  resources :reports, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
    has_many :moves
    has_one :forum
    has_many :favorites
    has_many :users, through: :favorites

    def proper_name
        self.name.split("-").map(&:capitalize).join(" ")
    end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :character

  validates_uniqueness_of :user_id, :scope => :character_id
end

app/models/forum.rb
class Forum < ApplicationRecord
    belongs_to :character
    has_many :posts
    has_many :users, through: :posts

    def character_name
        self.character.proper_name
    end

    def last_post
        posts.last
    end

    def last_user 
        last_post.user
    end

    def last_user_pic
        last_user.pic
    end

    def last_user_name
        last_user.username
    end

    def last_post_time
        last_post.last_edit
    end

    def content
        last_post.content
    end
end

app/models/move.rb
class Move < ApplicationRecord
    belongs_to :character
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :forum
    belongs_to :user
    has_many :reports

    paginates_per 5

    validates :content, length: { maximum: 500 }


    def username
        user.username
    end

    def self.size
        Post.all.size
    end

    def page
        ((forum.posts.all.find_index(self) + 1)/5) + 1
    end

    def user_pic
        user.pic
    end

    def user_location
        user.location
    end

    def last_edit
        if created_at == updated_at
            return "Created on: #{created_at.strftime("%m/%d/%Y at %I:%M%p")}"   
        else
            return "Edited on: #{updated_at.strftime("%m/%d/%Y at %I:%M%p")}"
        end
    end
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :forums, through: :posts
    has_many :favorites, dependent: :destroy
    has_many :characters, through: :favorites
    has_many :reports, through: :posts, dependent: :destroy

    validates :username, presence: true
    validates :username, uniqueness: true

    has_secure_password
    

    def pic
        if self.picture_link
            return picture_link
        else
            return "//style.anu.edu.au/_anu/4/images/placeholders/person.png"
        end
    end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

    def index
        @characters = Character.all
    end

    def show
        @favorite = Favorite.new
        @character = Character.find(params[:id])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
    def create
        return head(:forbidden) unless logged_in?
        Favorite.create(user_id: session[:user_id], character_id: params[:character_id])
        redirect_to request.referer
    end

    def destroy
        @favorite = Favorite.find(params[:id])
        @favorite.destroy
        redirect_to request.referer
    end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

    def index
        @forums = Forum.all
    end

    def show
        @forum = Forum.find(params[:id])
        @posts = @forum.posts.order(:id).page(params[:page])
        @post = Post.new
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:destroy, :edit, :update]

    def create
        @post = Post.new(post_params)
        @post.user = current_user
        if @post.save
            redirect_to forum_path(params[:forum_id])
        else
            render forum_path(params[:forum_id])
        end
    end

    def edit
        session[:return_to] ||= request.referer
        return head(:forbidden) unless current_user == @post.user
    end

    def update
        if @post.update(post_params)
            redirect_to session.delete(:return_to)
        else
            render :edit
        end
    end

    def destroy
        @post.destroy
        redirect_to session.delete(:return_to)
    end

    private

    def post_params
        params.permit(:content, :forum_id)
    end

    private

    def set_post
        @post = Post.find(params[:id])
    end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    
    def new
        @report = Report.new
    end

    def create
        @report = Report.new(params.permit(:notes))
        @report.post = Post.find(params[:post_id])
        @report.save
        flash[:success] = "USER REPORTED!"
        flash[:post_id] = @report.post.id
        ReportMailer.with(report: @report).new_report_email.deliver_later
        redirect_to forum_path(@report.post.forum)
    end

    def destroy
        @report = Report.find(params[:id])
        @report.delete
        redirect_to user_path(current_user)
    end

    def approve
        @report = Report.find(params[:id])
        @report.post.user.destroy
        @report.destroy
        redirect_to user_path(current_user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


    def welcome

    end

    def new
        return head(:forbidden) unless logged_in? == false
        session[:return_to] ||= request.referer
        @user = User.new
    end

    def create
        if User.exists?(username: params[:username])
            @user = User.find_by(username: params[:username])
            return head(:forbidden) unless @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to session.delete(:return_to)
        else
            flash[:error] = "Please Enter Username and Password"
            render :new
        end
    end

    def destroy
        session[:return_to] ||= request.referer
        session.delete :user_id
        redirect_to session.delete(:return_to)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update]

    def show
        if admin?
            @reports = Report.all
        end
    end

    def new
        return head(:forbidden) unless logged_in? == false
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def edit
        return head(:forbidden) unless current_user == @user
    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.permit(:username, :password, :password_confirmation, :location, :picture_link, :bio)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ban_requests_helper.rb
module BanRequestsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/characters/index.html.erb
<html>
    <div class="CharacterIndex">
       <% @characters.each do |character| %>
            <div>
                <figure id="Image">
                    <%= image_tag(character.image_url) %>
                </figure>
                <%= link_to character.proper_name, character_path(character), :class => "button has-background-danger is-outlined is-focused is-fullwidth" %>
            </div>
        <% end %>
    </div>  
</html>  

app/views/characters/show.html.erb
<nav class="level has-background-black-bis">
    <div class="level-left">
        <div class="level-item">
            <div id="CharacterTitle">
            <figure id="BigImage">
                <%= image_tag(@character.image_url) %>
            </figure>
            <h1 class="box has-text-danger has-background-warning has-text-centered	is-size-2 has-text-weight-bold"><%= @character.proper_name%></h1>
        </div>
        </div>
    </div>
    <div class="level-item">
        
    </div>
    <div class="level-right">
        <div class="level-item">
            <div class="buttons">
                <%= link_to "Link to Forum", forum_path(@character.forum), :class => "button has-background-danger is-outlined is-focused" %>
                <% if logged_in? %>
                    <% if current_user.characters.include?(@character)%>
                        <% @favorite = Favorite.find_by(user: current_user, character: @character)%>
                        <%= link_to "Unfavorite", favorite_path(@favorite), method: :delete, :class => "button has-background-danger is-outlined is-focused is-pulled-right" %>
                    <% else %>
                        <%= link_to "Favorite", favorites_path(character_id: @character.id), method: :post, :class => "button has-background-danger is-outlined is-focused is-pulled-right" %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</nav>
<div>
    <table class="table is-hoverable is-bordered has-background-danger is-paddingless is-marginless">
        <tr>
            <th>Command</th>
            <th>Hit Level</th>
            <th>Damage</th>
            <th>Startup</th>
            <th>Block</th>
            <th>Hit</th>
            <th>CounterHit</th>
            <th>Notes</th>
        </tr>

        <% @character.moves.each do |move| %>
        <tr>
            <td><%= move.command %></td>
            <td><%= move.level %></td>
            <td><%= move.damage %></td>
            <td><%= move.startup %></td>
            <td><%= move.block %></td>
            <td><%= move.hit %></td>
            <td><%= move.ch %></td>
            <td><%= move.notes %></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/forums/index.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container" id="NoBackground">
      <h1 class="title">
        Forum Index
      </h1>
      <h2 class="subtitle">
        With links to each forum
      </h2>
    </div>
  </div>
</section>


<% @forums.each do |forum| %>
    <article class="media has-text-white has-background-black is-paddingless is-marginless">
        <figure class="media-left is-paddingless is-marginless" id="Profile">
            <figure id="Image">
                <%= image_tag(forum.character.image_url) %>
            </figure>
            <%= link_to "To Forum", forum_path(forum), :class => "button has-background-danger is-outlined is-focused is-fullwidth" %>
        </figure>
            <div class="media-content is-marginless is-paddingless" id="IndexBox">
                <div class="content">
                    <p>
                        <strong id="BigLetters">Last Post:</strong>
                        <br>
                        <%= forum.content%>
                    </p>
                    <div id="PostFooter"><%= forum.last_post_time %></div>
                    </div>
                </div>
            <div class="media-right is-marginless is-paddingless" id="Box">
                <p class="image" id="Image">
                    <%= image_tag(forum.last_user_pic) %>
                </p>
                <p><%= forum.last_user_name %></p>
            </div>
        </article>
<% end %>

app/views/forums/show.html.erb
<% flash.now[:post] = params[:flash_notice] if params[:flash_notice] %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-background-warning is-bold">
        <%= @forum.character_name %>
      </h1>
    </div>
  </div>
</section>
<% @posts.each do |post| %>
<% if post.id == flash[:post].to_i%>
  <article class="media has-text-black has-background-warning is-paddingless is-marginless">
<% else %>
  <article class="media has-text-white has-background-black is-paddingless is-marginless">
<% end %>
  <figure class="media-left is-paddingless is-marginless" id="Profile">
    <p class="image" id="Image">
      <%= image_tag(post.user_pic) %>
    </p>
    <p id="location"><%= "Location: #{post.user_location}" %></p>
  </figure>
  <div class="media-content is-marginless" id="ContentBox">
    <div class="content">
      <p>
        <strong id="username"><%=link_to post.username, user_path(post.user)%></strong>
        <br>
        <%= post.content%>
      </p>
    </div>
    <nav class="level is-mobile">
      <div class="level-left">
        <a class="level-item">
          <p><%= post.last_edit %></p>
        </a>
      </div>
    </nav>
  </div>
  <div class="media-right">
    <% if post.user == current_user %>
        <%= link_to "Edit Post", edit_post_path(post), :class => "button has-background-danger is-outlined is-focused" %>
    <% end %>
    <% if logged_in? && post.user != current_user && !post.user.admin%>
      <%= link_to "Report User", new_report_path(post_id: post.id), :class => "button has-background-danger is-outlined is-focused" %>
    <% end %>
    <% if post.id == flash[:post_id] %>
          <div id="Warning">
            <%= flash[:success] %>
          </div>
        <% end %>
  </div>
</article>
<% end %>
<% if logged_in?%>
<article class="media">
  <figure class="media-left">
    <p class="image is-128x128">
      <%= image_tag(current_user.pic) %>
    </p>
  </figure>
  <div class="media-content">
  <form action="/posts" method="post">
    <div class="field">
      <p class="control">
        <textarea class="textarea has-text-white has-background-black" name="content" placeholder="Make a post..."></textarea>
      </p>
    </div>
    <nav class="level">
      <div class="level-left">
        <div class="level-item">
            <%= hidden_field_tag :forum_id, @forum.id %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
          <input type="submit" value="Add New Post" class="button is-danger">
        </div>
      </div>
    </nav>
  </form>
  </div>
</article>
<% else %>
    <section class="hero is-success is-marginless is-paddingless is-marginless">
        <div class="hero-body">
            <div class="container">
            <h1 class="title has-background-success is-bold">
                <%= "Log in to make a post" %>
            </h1>
            </div>
        </div>
    </section>
<% end %>
<% if @post.errors.any? %>
  <section class="hero is-danger">
    <div class="hero-body">
      <div class="container" id="NoBackground">
        <h1 class="title">
          Error:
        </h1>
        <h2 class="subtitle">
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </h2>
      </div>
    </div>
  </section>
<% end %> <br>
<%= paginate @posts %>

app/views/posts/edit.html.erb
<article class="media">
  <figure class="media-left">
    <p class="image is-128x128">
      <%= image_tag(current_user.pic) %>
    </p>
  </figure>
  <div class="media-content">
  <%= form_for @post do |f| %>
    <div class="field">
      <p class="control">
        <textarea class="textarea has-text-white has-background-black" name="content"><%= @post.content %></textarea>
      </p>
    </div>
    <nav class="level">
      <div class="level-left">
        <div class="level-item">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
            <div class="buttons">
                <input type="submit" value="Submit" class="button is-danger is-outlined is-focused"><br>
                <%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, :class => "button has-background-danger is-outlined is-focused is-pulled-right" %>
            </div>
        </div>
      </div>
    </nav>
  <% end %>
  </div>
</article>

<% if @post.errors.any? %>
  <section class="hero is-danger">
    <div class="hero-body">
      <div class="container" id="NoBackground">
        <h1 class="title">
          Error:
        </h1>
        <h2 class="subtitle">
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </h2>
      </div>
    </div>
  </section>
<% end %>

app/views/users/edit.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-background-warning is-bold">
        Edit User Form
      </h1>
    </div>
  </div>
</section>


<%= form_for @user do |f| %>
    <div class="field">
      <label class="label has-text-light">Username:</label>
      <div class="control">
         <input class="input" type="text" name="username" value=<%= @user.username %>>
      </div>
    </div>
    <div class="field">
      <label class="label has-text-light">Location:</label>
      <div class="control">
         <input class="input" type="text" name="location" value=<%= @user.location %>>
      </div>
    </div>
    <div class="field">
      <label class="label has-text-light">Avatar Image Link:</label>
      <div class="control">
         <input class="input" type="text" name="picture_link" value=<%= @user.pic  %>>
      </div>
    </div>
    <div class="field">
      <p class="control">
      <label class="label has-text-light">Bio:</label>
        <textarea class="textarea" name="bio" ><%= @user.bio %></textarea>
      </p>
    </div>
    <div class="buttons">
        <input type="submit" value="Submit" class="button is-danger is-outlined is-focused"><br>
    </div>
<% end %>

<% if @user.errors.any? %>
  <section class="hero is-danger">
    <div class="hero-body">
      <div class="container" id="NoBackground">
        <h1 class="title">
          Error:
        </h1>
        <h2 class="subtitle">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </h2>
      </div>
    </div>
  </section>
<% end %>

app/views/users/new.html.erb
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title has-background-warning is-bold">
        New User Sign-Up
      </h1>
    </div>
  </div>
</section>

<%= form_for @user do |f| %>
    <div class="field">
      <label class="label has-text-light">Username:</label>
      <div class="control">
         <input class="input" type="text" name="username" placeholder="Username">
      </div>
    </div>
    <div class="field">
      <label class="label has-text-light">Password:</label>
      <div class="control">
         <input class="input" type="password" name="password" placeholder="Password">
      </div>
    </div>
    <div class="field">
      <label class="label has-text-light">Confirm Password:</label>
      <div class="control">
         <input class="input" type="password" name="password_confirmation" placeholder="Password">
      </div>
    </div>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
    <div class="buttons">
        <input type="submit" value="Submit" class="button is-danger is-outlined is-focused"><br>
    </div>
<% end %>

<% if @user.errors.any? %>
  <section class="hero is-danger">
    <div class="hero-body">
      <div class="container" id="NoBackground">
        <h1 class="title">
          Error:
        </h1>
        <h2 class="subtitle">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </h2>
      </div>
    </div>
  </section>
<% end %>

app/views/users/show.html.erb
<div class="tile is-ancestor has-background-black">
  <div class="tile is-vertical is-8">
    <div class="tile">
      <div class="tile is-parent is-vertical">
        <article class="tile is-child notification is-success">
          <p class="title"><%= @user.username %></p>
          <% if @user == current_user %>
            <%= button_to "Edit Profile", edit_user_path(@user), method: :get, :class => "button has-background-danger is-outlined is-focused" %>
            <% end %>
        </article>
        <article class="tile is-child notification is-warning">
          <p class="title">Location</p>
          <p class="subtitle"><%= @user.location %></p>
        </article>
      </div>
      <div class="tile is-parent">
        <article class="tile is-child notification is-info">
          <figure class="image" id="ProfileImage">
            <%= image_tag(@user.pic) %>
          </figure>
        </article>
      </div>
    </div>
    <div class="tile is-parent">
      <article class="tile is-child notification is-danger">
        <p class="title">Bio:</p>
        <div class="content">
          <%= @user.bio %>
        </div>
      </article>
    </div>
  </div>
  <div class="tile is-parent">
    <article class="tile is-child notification is-success">
      <div class="content">
        <p class="title">Favorite Characters:</p>
        <div class="content">
          <div class="buttons">
            <% @user.characters.each do |character| %>
              <%= link_to character.proper_name, character_path(character), :class => "button has-background-danger is-outlined is-focused is-fullwidth" %>
            <% end %>
          </div>
        </div>
      </div>
    </article>
  </div>
</div>
<% if admin? && @user == current_user%>
  <section class="hero is-warning">
    <div class="hero-body">
      <div class="container" id="NoBackground">
        <h1 class="title">
          Reported Posts:
        </h1>
        <h2 class="buttons">
            <% @reports.all.each do |request| %>
            <div class="box has-background-black has-text-white">
              <article class="media">
                <div class="media-left">
                  <p class="image" id="Image">
                    <%= image_tag(request.post.user_pic) %>
                  </p>
                </div>
                <div class="media-content">
                  <div class="content">
                    <p>
                      <strong><%= request.post.username %></strong> 
                      <br>
                      <%= request.notes%>
                    </p>
                  </div>
                <nav class="level is-mobile">
                  <%= link_to "post", forum_path(request.post.forum, flash_notice: request.post.id, page: request.post.page), :class => "button has-background-danger is-outlined is-focused" %>
                </nav>
      </div>
      <div class="media-right">
                  <h2 >
                    <%= button_to "Approve", ban_path(id: request.id), method: :delete, :class => "button has-background-danger is-outlined is-focused is-fullwidth"%>
                    <%= button_to "Deny", report_path(request), method: :delete, :class => "button has-background-danger is-outlined is-focused is-fullwidth" %>
                </h2>
                </div>
    </article>
</div>
              
            <% end %>
        </h2>
      </div>
    </div>
  </section>
<% end %>