config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  delete '/ban' => 'reports#approve'
  
  resources :posts, only: [:edit, :create, :update, :destroy]
  resources :forums, only: [:index, :show] do
    get 'page/:page', action: :show, on: :collection
  end
  resources :characters, only: [:show, :index]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy]
  resources :reports, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
    has_many :moves
    has_one :forum
    has_many :favorites
    has_many :users, through: :favorites

    def proper_name
        self.name.split("-").map(&:capitalize).join(" ")
    end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :character

  validates_uniqueness_of :user_id, :scope => :character_id
end

app/models/forum.rb
class Forum < ApplicationRecord
    belongs_to :character
    has_many :posts
    has_many :users, through: :posts

    def character_name
        self.character.proper_name
    end

    def last_post
        posts.last
    end

    def last_user 
        last_post.user
    end

    def last_user_pic
        last_user.pic
    end

    def last_user_name
        last_user.username
    end

    def last_post_time
        last_post.last_edit
    end

    def content
        last_post.content
    end
end

app/models/move.rb
class Move < ApplicationRecord
    belongs_to :character
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :forum
    belongs_to :user
    has_many :reports

    paginates_per 5

    validates :content, length: { maximum: 500 }


    def username
        user.username
    end

    def self.size
        Post.all.size
    end

    def page
        ((forum.posts.all.find_index(self) + 1)/5) + 1
    end

    def user_pic
        user.pic
    end

    def user_location
        user.location
    end

    def last_edit
        if created_at == updated_at
            return "Created on: #{created_at.strftime("%m/%d/%Y at %I:%M%p")}"   
        else
            return "Edited on: #{updated_at.strftime("%m/%d/%Y at %I:%M%p")}"
        end
    end
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :forums, through: :posts
    has_many :favorites, dependent: :destroy
    has_many :characters, through: :favorites
    has_many :reports, through: :posts, dependent: :destroy

    validates :username, presence: true
    validates :username, uniqueness: true

    has_secure_password
    

    def pic
        if self.picture_link
            return picture_link
        else
            return "//style.anu.edu.au/_anu/4/images/placeholders/person.png"
        end
    end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

    def index
        @forums = Forum.all
    end

    def show
        @forum = Forum.find(params[:id])
        @posts = @forum.posts.order(:id).page(params[:page])
        @post = Post.new
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:destroy, :edit, :update]

    def create
        @post = Post.new(post_params)
        @post.user = current_user
        if @post.save
            redirect_to forum_path(params[:forum_id])
        else
            render forum_path(params[:forum_id])
        end
    end

    def edit
        session[:return_to] ||= request.referer
        return head(:forbidden) unless current_user == @post.user
    end

    def update
        if @post.update(post_params)
            redirect_to session.delete(:return_to)
        else
            render :edit
        end
    end

    def destroy
        @post.destroy
        redirect_to session.delete(:return_to)
    end

    private

    def post_params
        params.permit(:content, :forum_id)
    end

    private

    def set_post
        @post = Post.find(params[:id])
    end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    
    def new
        @report = Report.new
    end

    def create
        @report = Report.new(params.permit(:notes))
        @report.post = Post.find(params[:post_id])
        @report.save
        flash[:success] = "USER REPORTED!"
        flash[:post_id] = @report.post.id
        ReportMailer.with(report: @report).new_report_email.deliver_later
        redirect_to forum_path(@report.post.forum)
    end

    def destroy
        @report = Report.find(params[:id])
        @report.delete
        redirect_to user_path(current_user)
    end

    def approve
        @report = Report.find(params[:id])
        @report.post.user.destroy
        @report.destroy
        redirect_to user_path(current_user)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update]

    def show
        if admin?
            @reports = Report.all
        end
    end

    def new
        return head(:forbidden) unless logged_in? == false
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def edit
        return head(:forbidden) unless current_user == @user
    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.permit(:username, :password, :password_confirmation, :location, :picture_link, :bio)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ban_requests_helper.rb
module BanRequestsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TekkenBooks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="header">
  <div class="container">
    <nav class="level">
      <div class="level-left">
        <div class="level-item">
          <div class="buttons">
            <%= link_to("Home", root_path, :class => "button has-background-danger is-outlined") %>
            <%= link_to("Characters", characters_path, :class => "button has-background-danger is-outlined") %>
            <%= link_to("Forums", forums_path, :class => "button has-background-danger is-outlined") %>
          </div>
        </div>
      </div>
      <div class="level-item" id="imageHeader">
        <figure class="image is-256x256" id="tekken">
          <img src="https://ksassets.timeincuk.net/wp/uploads/sites/54/2016/06/tekken-7-logo-1-920x518.png">
        </figure>
      </div>
      <div class="level-right">
        <div class="level-item">
          <div class="buttons">
            <% if logged_in? %>
              <%= link_to("Profile Page", user_path(current_user), :class => "button has-background-danger is-outlined") %>
              <%= button_to "Log Out", logout_path, action: "delete" , :class => "button has-background-danger is-outlined"%>
            <% else %>
              <%= link_to("Log In", login_path, :class => "button has-background-danger is-outlined") %>
              <%= link_to("Sign Up", new_user_path, :class => "button has-background-danger is-outlined") %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  </div>
</header>
<section class="section">
  <div class="container">
    <%= yield %>
  </div>
</section>
<footer class="footer has-background-black has-text-white">
  <div class="container">
    Made by Mitch :)
  </div>
</footer>
  </body>
</html>